apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    app: focusboard-cache
  ports:
    - port: {{ .Values.cache.service.port }}
      targetPort: {{ .Values.cache.service.targetPort }}