apiVersion: apps/v1
kind: Deployment
metadata:
  name: focusboard-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: focusboard-web
  template:
    metadata:
      labels:
        app: focusboard-web
    spec:
      containers:
        - name: web
          image: nedakh126/focusboard-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: focusboard-web-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: focusboard-web-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: focusboard-web-config
                  key: DB_NAME
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: focusboard-web-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: focusboard-web-config
                  key: REDIS_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: focusboard-web-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: focusboard-web-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: focusboard-web-secret
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3