web:
  replicaCount: 2
  image:
    repository: nedakh126/focusboard-web
    tag: latest
    pullPolicy: Always
  containerPort: 5000
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 30007

db:
  replicaCount: 1
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  containerPort: 5432
  service:
    port: 5432
    targetPort: 5432
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
  

cache:
  replicaCount: 1
  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent
  containerPort: 6379
  service:
    port: 6379
    targetPort: 6379

config:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: focusboard
  REDIS_HOST: cache
  REDIS_PORT: "6379"

secret:
  DB_USER: focususer
  DB_PASSWORD: focuspass
  SECRET_KEY: change-this-secret-key

ingress:
  enabled: true
  className: nginx
  host: focusboard.local
  path: /
  pathType: Prefix