apiVersion: apps/v1
kind: Deployment
metadata:
  name: focusboard-db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: focusboard-db
  template:
    metadata:
      labels:
        app: focusboard-db
    spec:
      containers:
        - name: db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.db.containerPort }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.config.DB_NAME | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.secret.DB_USER | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.secret.DB_PASSWORD | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: focusboard-db-pvc