apiVersion: v1
kind: Service
metadata:
  name: focusboard-web-service
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: focusboard-web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      nodePort: {{ .Values.web.service.nodePort }}