apiVersion: v1
kind: Secret
metadata:
  name: focusboard-web-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | quote }}